name: "Oficina IaC - Destroy"

# 1. GATILHO: Dispara APENAS manualmente pelo botão na interface do GitHub
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Baixa o código do repositório
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Injeta as credenciais temporárias do AWS Labs
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      # Step 3: Instala o Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      # Step 4: Inicializa o Terraform (conecta no S3 para ler o tfstate)
      - name: Terraform Init
        run: terraform init

      # Step 5: Executa a destruição automatizada na AWS
      - name: Terraform Destroy
        env:
          TF_VAR_aws_region: ${{ vars.AWS_DEFAULT_REGION }}
          TF_VAR_customer_jwt_secret: ${{ secrets.CUSTOMER_JWT_SECRET }}
          TF_VAR_new_relic_license_key: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
        run: terraform destroy -auto-approve -input=false